import { Course, TimetableEntry } from "../types/course.types";

export const COURSES: Course[] = [
  {
    id: '1',
    code: 'CSC307',
    department: 'Computer Science',
    title: 'AI & Machine Learning',
    description: 'Supervised learning neural networks, NLP basics',
    type: 'Elective',
    units: 2,
    levels: ['300L', '400L'],
    mode: 'On-Site',
    schedule: 'Thursday 14:00 - 16:00',
    lecturer: 'Dr. Adeyemi Bolaji',
    status: 'Pending',
  },
  {
    id: '2',
    code: 'CSC401',
    department: 'Computer Science',
    title: 'Final Year Project 1',
    description: 'Research methodology proposal writing',
    type: 'Required',
    units: 4,
    levels: ['400L'],
    mode: 'Online',
    schedule: 'Thursday 8:00 - 10:00',
    lecturer: 'Dr. Adeyemi Bolaji',
    status: 'Approved',
  },
  {
    id: '3',
    code: 'CSC201',
    department: 'Computer Science',
    title: 'Data Structures & Algorithms',
    description: 'Arrays, linked lists, trees, sorting algorithms',
    type: 'Core',
    units: 3,
    levels: ['200L'],
    mode: 'On-Site',
    schedule: 'Monday 10:00 - 12:00',
    lecturer: 'Dr. Adeyemi Bolaji',
    status: 'Approved',
  },
  {
    id: '4',
    code: 'CSC301',
    department: 'Computer Science',
    title: 'Software Engineering',
    description: 'SDLC, design patterns, agile methodologies',
    type: 'Core',
    units: 3,
    levels: ['300L'],
    mode: 'On-Site',
    schedule: 'Wednesday 9:00 - 11:00',
    lecturer: 'Dr. Adeyemi Bolaji',
    status: 'Approved',
  },
  {
    id: '5',
    code: 'GST211',
    department: 'General Studies',
    title: 'Use of English & Communication Skills II',
    description: 'Academic writing and presentation skills',
    type: 'Required',
    units: 2,
    levels: ['200L'],
    mode: 'On-Site',
    schedule: 'Tuesday 8:00 - 10:00',
    lecturer: 'Dr. Adeyemi Bolaji',
    status: 'Approved',
  },
  {
    id: '6',
    code: 'CSC405',
    department: 'Computer Science',
    title: 'Computer Networks',
    description: 'OSI model, TCP/IP, routing protocols',
    type: 'Borrowed',
    units: 3,
    levels: ['400L'],
    mode: 'Hybrid',
    schedule: 'Friday 13:00 - 15:00',
    lecturer: 'Dr. Adeyemi Bolaji',
    status: 'Pending',
  },
];
 
export const TIMETABLE: TimetableEntry[] = [
  { day: 'Monday',    time: '10:00 - 12:00', course: 'Data Structures & Algorithms', code: 'CSC201', room: 'LT 3', level: '200L' },
  { day: 'Tuesday',   time: '08:00 - 10:00', course: 'Use of English II',             code: 'GST211', room: 'LT 1', level: '200L' },
  { day: 'Wednesday', time: '09:00 - 11:00', course: 'Software Engineering',          code: 'CSC301', room: 'LT 2', level: '300L' },
  { day: 'Thursday',  time: '08:00 - 10:00', course: 'Final Year Project 1',          code: 'CSC401', room: 'Online', level: '400L' },
  { day: 'Thursday',  time: '14:00 - 16:00', course: 'AI & Machine Learning',         code: 'CSC307', room: 'LT 4', level: '300L' },
  { day: 'Friday',    time: '13:00 - 15:00', course: 'Computer Networks',             code: 'CSC405', room: 'LT 2', level: '400L' },
];
 
export const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];
 